import type {FramePlan} from './playback';
export type PluginToRuntimeMessage={v:1;type:'cells-ready';deviceId:string}|{v:1;type:'key';phase:'down'|'up';index:number;generation:string}|{v:1;type:'frame-sent';generation:string;frame:number}|{v:1;type:'lock';locked:boolean}|{v:1;type:'pong'};
export type PresentationTrigger='initial'|'page'|'unlock'|'reconnect'|'refresh'|'standby';
export type PresentationDelivery='immediate'|'prepare'|'resume';
export type RuntimeToPluginMessage={v:1;type:'presentation';trigger:PresentationTrigger;delivery:PresentationDelivery;plan:FramePlan;inputEnabled:boolean;startKeys?:readonly string[]}|{v:1;type:'input';enabled:boolean}|{v:1;type:'ping'};
const object=(x:unknown)=>{if(!x||typeof x!=='object'||Array.isArray(x))throw new Error('Expected protocol object');return x as Record<string,unknown>};const exact=(x:Record<string,unknown>,keys:string[])=>{if(Object.keys(x).some(k=>!keys.includes(k)))throw new Error('Unknown protocol field')};const gen=(x:unknown)=>{if(typeof x!=='string'||!/^[A-Za-z0-9_-]{1,64}$/.test(x))throw new Error('Invalid generation');return x};
export function parsePluginMessage(raw:unknown):PluginToRuntimeMessage{const x=object(raw);if(x.v!==1)throw new Error('Unsupported protocol version');if(x.type==='cells-ready'){exact(x,['v','type','deviceId']);if(typeof x.deviceId!=='string'||!x.deviceId||x.deviceId.length>128)throw new Error('Invalid device');return x as PluginToRuntimeMessage;}if(x.type==='key'){exact(x,['v','type','phase','index','generation']);if(!['down','up'].includes(x.phase as string)||!Number.isInteger(x.index)||(x.index as number)<0||(x.index as number)>14)throw new Error('Invalid key');gen(x.generation);return x as PluginToRuntimeMessage;}if(x.type==='frame-sent'){exact(x,['v','type','generation','frame']);gen(x.generation);if(!Number.isInteger(x.frame)||(x.frame as number)<0||(x.frame as number)>14)throw new Error('Invalid frame');return x as PluginToRuntimeMessage;}if(x.type==='lock'){exact(x,['v','type','locked']);if(typeof x.locked!=='boolean')throw new Error('Invalid lock');return x as PluginToRuntimeMessage;}if(x.type==='pong'){exact(x,['v','type']);return x as PluginToRuntimeMessage;}throw new Error('Unknown plugin message');}
const image=(value:unknown,format:'png'|'any'='any')=>typeof value==='string'&&new RegExp(`^data:image\\/${format==='png'?'png':'(?:png|jpeg)'};base64,[A-Za-z0-9+/]+=*$`).test(value)&&value.length<=512_000;
const keys=(value:unknown,format:'png'|'any'='any')=>Array.isArray(value)&&value.length===15&&value.every(key=>image(key,format));
function plan(raw:unknown):FramePlan{const p=object(raw);exact(p,['generation','frames']);const generation=gen(p.generation);if(!Array.isArray(p.frames)||!p.frames.length||p.frames.length>15)throw new Error('Invalid frames');let prior=-1;const frames=p.frames.map((rawFrame,i)=>{const f=object(rawFrame);exact(f,['index','offsetMs','keys']);if(f.index!==i||!Number.isFinite(f.offsetMs)||(f.offsetMs as number)<0||(f.offsetMs as number)<=prior||!keys(f.keys))throw new Error('Invalid frame');prior=f.offsetMs as number;return{index:i,offsetMs:prior,keys:f.keys as string[]};});return{generation,frames};}
export function parseRuntimeMessage(raw:unknown):RuntimeToPluginMessage{const x=object(raw);if(x.v!==1)throw new Error('Unsupported protocol version');if(x.type==='presentation'){exact(x,['v','type','trigger','delivery','plan','inputEnabled','startKeys']);const delivery=x.delivery===undefined?'immediate':x.delivery;if(!['initial','page','unlock','reconnect','refresh','standby'].includes(x.trigger as string)||!['immediate','prepare','resume'].includes(delivery as string)||typeof x.inputEnabled!=='boolean')throw new Error('Invalid presentation');if(delivery!=='immediate'&&(x.trigger!=='unlock'||!keys(x.startKeys,'png')))throw new Error('Invalid prepared presentation');if(delivery==='immediate'&&x.startKeys!==undefined&&!keys(x.startKeys,'png'))throw new Error('Invalid start keys');return{v:1,type:'presentation',trigger:x.trigger as PresentationTrigger,delivery:delivery as PresentationDelivery,plan:plan(x.plan),inputEnabled:x.inputEnabled,...(x.startKeys===undefined?{}:{startKeys:x.startKeys as string[]})};}if(x.type==='input'){exact(x,['v','type','enabled']);if(typeof x.enabled!=='boolean')throw new Error('Invalid input');return x as RuntimeToPluginMessage;}if(x.type==='ping'){exact(x,['v','type']);return x as RuntimeToPluginMessage;}throw new Error('Unknown runtime message');}
