import {describe,expect,test} from 'bun:test';import sharp from 'sharp';import {createHash} from 'node:crypto';import {defaultStudioDocument,singlePressBehavior} from '../studio/document';import {composeButton} from './button-compositor';import {DeckVisualRenderer} from './render';
describe('DeckVisualRenderer',()=>{test('uses one identified background canvas and leaves hidden occupied cells untouched',async()=>{const doc=defaultStudioDocument(),page=doc.pages[0];page.appearance={color:'#ff0000'};page.buttons=[{id:'hidden',index:0,behavior:singlePressBehavior({type:'none'}),appearance:{contentMode:'hidden'}}];const deck={index:0,pageCount:1,epoch:0,keys:Array.from({length:15},(_,index)=>({type:'empty' as const,index}))};const result=await new DeckVisualRenderer().render(doc,page,deck,{read:async()=>Buffer.alloc(0)});expect(result.keyPngs).toHaveLength(15);expect(result.keyPngs.every(Buffer.isBuffer)).toBe(true);expect(result.identity).toBe(createHash('sha256').update(result.png).digest('hex'));expect(result).not.toHaveProperty('keys');const pixel=await sharp(result.png).raw().toBuffer();expect([...pixel.subarray(0,3)]).toEqual([255,0,0]);});});

test('DeckVisualRenderer uses the shared compositor for fixed buttons',async()=>{
  const iconId='a'.repeat(64),icon=await sharp({create:{width:12,height:12,channels:4,background:'#0000ff'}}).png().toBuffer(),assets={read:async(id:string)=>{if(id!==iconId)throw new Error('missing');return icon;}};
  const document=defaultStudioDocument(),page=document.pages[0];page.appearance={color:'#221100'};page.buttons=[{id:'fixed',index:0,behavior:singlePressBehavior({type:'none'}),appearance:{contentMode:'icon-and-label',icon:{assetId:iconId,fit:'contain'},label:{text:'Run',position:'bottom',size:'medium',color:'#ffffff'}}}];
  const deck={index:0,pageCount:1,epoch:0,keys:Array.from({length:15},(_,index)=>index===0?{type:'tile' as const,index,label:'Run',enabled:false}:{type:'empty' as const,index})};
  const result=await new DeckVisualRenderer().render(document,page,deck,assets),actual=result.keyPngs[0],background=await sharp({create:{width:72,height:72,channels:4,background:'#221100'}}).png().toBuffer(),expected=await composeButton({appearance:page.buttons[0].appearance,background,assets,runtime:{label:'Run'}});
  expect(actual.toString('hex')).toBe(expected.toString('hex'));
});

test('DeckVisualRenderer projects a GitHub pipeline snapshot onto an authored fixed button',async()=>{
  const document=defaultStudioDocument(),page=document.pages[0];page.appearance={color:'#101010'};page.buttons=[{id:'stg',index:0,behavior:singlePressBehavior({type:'github-pipeline',pipelineId:'crepe-backend-stg',role:'deployment'}),appearance:{contentMode:'label-only',label:{text:'Stg 배포',position:'center',size:'medium',color:'#ffffff'}}}];
  const deck={index:0,pageCount:1,epoch:0,keys:Array.from({length:15},(_,index)=>index===0?{type:'tile' as const,index,label:'Stg 배포',enabled:false}:{type:'empty' as const,index})},assets={read:async()=>Buffer.alloc(0)};
  const result=await new DeckVisualRenderer().render(document,page,deck,assets,{toggle:()=>undefined,pipeline:binding=>binding.pipelineId==='crepe-backend-stg'?{binding,state:'approval-required',detail:'승인 대기',color:'#f59e0b',runUrl:'https://github.com/cookieplace/crepe/actions/runs/1'}:undefined}),raw=await sharp(result.keyPngs[0]).raw().toBuffer();
  expect([...raw.subarray(0,3)]).toEqual([245,158,11]);
});
