import {StudioModel} from './model';import type {StudioButton,TransitionSpec} from '../../studio/document';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T,input=(id:string)=>$<HTMLInputElement>(id),select=(id:string)=>$<HTMLSelectElement>(id);type Bootstrap={token:string;snapshot:{document:any;version:string};draft?:any;sources:string[];runtimeStatus:any;geometry:{x:number[];y:number[]}};
let model:StudioModel,token='',version='',sources:string[]=[],geometry:{x:number[];y:number[]},standby=false,draftTimer:ReturnType<typeof setTimeout>;
const page=()=>model.document.pages.find(p=>p.id===model.selectedPageId)!;const selected=()=>page().buttons?.find(b=>b.index===model.selectedKey);
function error(message=''){$('error').hidden=!message;$('error').textContent=message;}function assetUrl(id?:string){return id?`/api/assets/${id}`:'';}
function status(){$('state').textContent=model.dirty?'적용하지 않은 변경':'장치와 동일';$<HTMLButtonElement>('apply').disabled=!model.dirty;}
function draw(){const p=page();$('crumb').textContent=standby?'대기 화면':`페이지 / ${p.title}`;$('title').textContent=standby?'잠금 중 표시할 화면':'버튼이 놓일 화면을 만드세요';const appearance=standby?model.document.standby:p.appearance;$('canvas').style.backgroundImage=appearance?.background?`url(${assetUrl(appearance.background.assetId)})`:'';$('canvas').style.backgroundColor=appearance?.color??'#000';$('canvas').style.backgroundSize=appearance?.background?.fit==='stretch'?'100% 100%':appearance?.background?.fit??'cover';select('fit').value=appearance?.background?.fit??'cover';
  const canvas=$('canvas');canvas.replaceChildren();for(let i=0;i<15;i++){const key=document.createElement('button');key.className='key'+(!standby&&i===model.selectedKey?' selected':'');key.style.left=`${geometry.x[i%5]}px`;key.style.top=`${geometry.y[Math.floor(i/5)]}px`;const b=!standby?p.buttons?.find(x=>x.index===i):undefined;if(b){const visual=document.createElement('span');visual.className='button-visual';visual.style.opacity=String(b.appearance?.opacity??1);if(b.appearance?.iconAssetId)visual.style.backgroundImage=`url(${assetUrl(b.appearance.iconAssetId)})`;visual.textContent=b.label??(b.type==='app'?'앱':b.type==='open'?'웹':'버튼');key.append(visual);}const n=document.createElement('small');n.textContent=String(i+1).padStart(2,'0');key.append(n);key.onclick=()=>{if(standby)return;model.selectKey(i);draw();};canvas.append(key);}
  const pages=$('pages');pages.replaceChildren(...model.document.pages.map(item=>{const button=document.createElement('button');button.className='page-row'+(!standby&&item.id===model.selectedPageId?' selected':'');button.append(Object.assign(document.createElement('b'),{textContent:'▦'}));const label=document.createElement('span');label.textContent=item.title;label.append(Object.assign(document.createElement('small'),{textContent:item.id}));button.append(label);button.onclick=()=>{standby=false;model.selectPage(item.id);draw();};return button;}));$('standby').classList.toggle('selected',standby);$('dynamic').hidden=standby;
  const b=selected();$('key-title').textContent=`버튼 ${model.selectedKey+1}`;$('position').textContent=`${Math.floor(model.selectedKey/5)+1}행 ${model.selectedKey%5+1}열 · 키 ${model.selectedKey+1}`;select('button-type').value=b?.type==='app'||b?.type==='open'||b?.type==='text'?b.type:'empty';input('button-label').value=b?.label??'';input('button-value').value=b?.type==='app'?b.bundleId:b?.type==='open'?b.url:'';input('opacity').value=String(Math.round((b?.appearance?.opacity??0)*100));$('opacity-value').textContent=input('opacity').value+'%';$('button-fields').hidden=!b;$('bundle-label').childNodes[0]!.textContent=select('button-type').value==='open'?'URL':'앱 Bundle ID';
  for(const trigger of ['pageChange','unlock','reconnect'] as const)select(trigger==='pageChange'?'page-motion':trigger+'-motion').value=model.document.motion[trigger].type;select('region-source').replaceChildren(...sources.map(s=>Object.assign(document.createElement('option'),{value:s,textContent:s})));const region=p.dynamicRegions?.[0];if(region){select('region-source').value=region.signals.source??sources[0]??'';input('region-keys').value=region.keys.map(k=>k+1).join(', ');}status();}
function changed(){draw();clearTimeout(draftTimer);draftTimer=setTimeout(()=>void fetch('/api/draft',{method:'POST',headers:{'Content-Type':'application/json','X-Streamhub-Editor':token},body:JSON.stringify({document:model.document})}),350);}
async function upload(file:File){const response=await fetch('/api/assets',{method:'POST',headers:{'X-Streamhub-Editor':token,'Content-Type':file.type||'application/octet-stream'},body:file});const body=await response.json();if(!response.ok)throw new Error(body.error);return body.assetId as string;}
input('background').onchange=async()=>{const file=input('background').files?.[0];if(!file)return;try{model.setBackground(standby?'standby':'page',await upload(file),select('fit').value as any);changed();}catch(e){error(String(e));}};select('fit').onchange=()=>{const appearance=standby?model.document.standby:page().appearance;if(appearance?.background){model.setBackground(standby?'standby':'page',appearance.background.assetId,select('fit').value as any);changed();}};
select('button-type').onchange=()=>{const type=select('button-type').value;if(type==='empty'){model.removeButton(model.selectedKey);changed();return;}const base={index:model.selectedKey,label:input('button-label').value||undefined,appearance:{opacity:Number(input('opacity').value)/100}};const button:StudioButton=type==='app'?{...base,type,bundleId:input('button-value').value||'org.mozilla.firefox'}:type==='open'?{...base,type,url:input('button-value').value||'https://example.com/'}:{...base,type:'text',label:input('button-label').value||'버튼'};model.setButton(button);changed();};
for(const id of ['button-label','button-value','opacity'])input(id).oninput=()=>{const b=selected();if(!b)return;const clone=structuredClone(b);clone.label=input('button-label').value||undefined;if(clone.type==='app')clone.bundleId=input('button-value').value;if(clone.type==='open')clone.url=input('button-value').value;clone.appearance={...clone.appearance,opacity:Number(input('opacity').value)/100};try{model.setButton(clone);changed();}catch{}};
input('icon').onchange=async()=>{const b=selected(),file=input('icon').files?.[0];if(!b||!file)return;try{model.setButton({...b,appearance:{...b.appearance,iconAssetId:await upload(file)}});changed();}catch(e){error(String(e));}};
$('add-page').onclick=()=>{standby=false;model.addPage();changed();};$('standby').onclick=()=>{standby=true;draw();};$('save-region').onclick=()=>{try{const keys=input('region-keys').value.split(',').map(v=>Number(v.trim())-1);model.setDynamicRegion({id:'dynamic',keys,signals:{source:select('region-source').value},order:'recent',overflow:'paginate',empty:'background'});changed();}catch(e){error(String(e));}};
for(const [id,trigger,duration] of [['page-motion','pageChange',280],['unlock-motion','unlock',480],['reconnect-motion','reconnect',360]] as const)select(id).onchange=()=>{model.setMotion(trigger,{type:select(id).value as TransitionSpec['type'],durationMs:select(id).value==='none'?0:duration});changed();};
$('undo').onclick=()=>{model.undo();draw();};$('redo').onclick=()=>{model.redo();draw();};$('apply').onclick=async()=>{try{const response=await fetch('/api/apply',{method:'POST',headers:{'Content-Type':'application/json','X-Streamhub-Editor':token},body:JSON.stringify({document:model.document,expectedVersion:version})}),body=await response.json();if(!response.ok)throw new Error(body.error);version=body.version;model.markApplied();$('runtime').textContent=body.runtimeStatus?.connected?'Stream Deck 연결됨':'저장됨 · Runtime 오프라인';draw();}catch(e){error(String(e));}};
async function load(){const response=await fetch('/api/bootstrap'),data=await response.json() as Bootstrap;token=data.token;version=data.snapshot.version;sources=data.sources;geometry=data.geometry;model=new StudioModel(data.draft??data.snapshot.document);$('runtime').textContent=data.runtimeStatus?.connected?'Stream Deck 연결됨':data.runtimeStatus?.message??'Runtime 오프라인';draw();}void load().catch(e=>error(String(e)));
