import {BoardHistory,duplicatePage,movePage,createTemplate} from '../editing';
import {CONTENT_KEYS} from '../../streamdeck';
import {validatePageConfig,type PageConfig,type PageDefinition,type PageButton} from '../../streamdeck/pages';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const input=(id:string)=>$<HTMLInputElement>(id);
const select=(id:string)=>$<HTMLSelectElement>(id);
let board:PageConfig={defaultPage:'home',pages:[{id:'home',title:'홈',signals:{}}]},selected='home',selectedKey=0,sources:string[]=[],version='',token='',saved='',mode:'run'|'edit'='run',ws:WebSocket|undefined,timer:ReturnType<typeof setTimeout>,ready=false,saving=false;
let runtime={pageId:'',manual:false,locked:false,inputEnabled:false,latencyMs:0,frames:0,keysSent:0,lastFrameMs:0};
const history=new BoardHistory(board);let copiedKey:PageButton|undefined;
const fieldErrors=new Map<string,string>();
const held=new Set<number>(),canvases:HTMLCanvasElement[]=[],keys:HTMLButtonElement[]=[];
const page=():PageDefinition=>board.pages.find(p=>p.id===selected)??board.pages[0]!;
const send=(message:unknown)=>{if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(message));};
function error(message=''){$('error').textContent=message;$('error').hidden=!message;}
function valid(){if(fieldErrors.size){error([...fieldErrors.values()].join(' '));return false;}try{validatePageConfig(board);return true;}catch(e){error(`설정을 확인하세요: ${(e as Error).message}`);return false;}}
function dirty(){return JSON.stringify(board)!==saved;}
function status(){const changed=dirty();$('save-state').textContent=saving?'저장 중…':changed?'미저장 변경':'저장됨';$('save-state').classList.toggle('dirty',changed);$<HTMLButtonElement>('save').disabled=!ready||saving||!changed;}
function changed(){history.push(board);historyStatus();status();clearTimeout(timer);timer=setTimeout(()=>{if(valid()){error();send({type:'draft',board,selectedPage:selected});}},120);}
function option(value:string,label:string){const o=document.createElement('option');o.value=value;o.textContent=label;return o;}
function drawPages(){const list=$('page-list');list.replaceChildren();for(const p of board.pages){const button=document.createElement('button');button.className='page-item';button.classList.toggle('selected',p.id===selected);button.setAttribute('aria-current',p.id===selected?'page':'false');const icon=document.createElement('span');icon.className='page-icon';icon.textContent='▦';icon.setAttribute('aria-hidden','true');const copy=document.createElement('span'),name=document.createElement('span'),sub=document.createElement('small');name.className='page-name';name.textContent=p.title||'이름 없는 페이지';sub.textContent=p.id+(p.id===board.defaultPage?' · 기본':'');copy.append(name,sub);button.append(icon,copy);button.onclick=()=>{releaseAll();selected=p.id;drawControls();if(valid())send({type:'page',pageId:selected});};list.append(button);}const active=select('active-app'),previous=active.value;active.replaceChildren(option('','일치하는 앱 없음'));for(const app of new Set(board.pages.flatMap(p=>p.match?.appBundleId?[p.match.appBundleId]:[])))active.append(option(app,app));active.value=previous;}
function drawControls(){fieldErrors.clear();drawPages();const p=page();$('preview-title').textContent=p.title;input('page-title').value=p.title;input('page-id').value=p.id;input('default-page').checked=board.defaultPage===p.id;$<HTMLButtonElement>('delete-page').disabled=board.pages.length===1;input('app-bundle').value=p.match?.appBundleId??'';select('window-mode').value=p.match?.windowTitle?.mode??'contains';input('window-value').value=p.match?.windowTitle?.value??'';input('display-match').value=p.match?.displayId??'';input('rule-priority').value=String(p.priority??0);const source=select('signal-source');source.replaceChildren(option('__none','신호 표시 안 함'),option('__all','모든 소스'));for(const s of new Set([...sources,...board.pages.flatMap(p=>p.signals?.source?[p.signals.source]:[])]))source.append(option(s,s));source.value=p.signals===undefined?'__none':p.signals.source??'__all';select('transition').value=board.transition??'fade';input('duration').value=String(board.durationMs??250);input('duration').disabled=board.transition==='none';drawKey();status();}
function drawKey(){const b=page().buttons?.find(b=>b.index===selectedKey);input('button-color').value=b?.color??(b?.type==='page'?'#62a9ff':b?.type==='auto'?'#76c8a1':'#24282e');select('button-icon').value=b?.icon??'';const capacity=CONTENT_KEYS.filter(index=>!page().buttons?.some(button=>button.index===index)).length;$('key-capacity').textContent=`자동 신호 자리 ${page().signals?capacity:0}개 · 고정 키 ${page().buttons?.length??0}개. 11·15번은 목록 탐색 자리입니다.`;keys.forEach((key,index)=>{key.classList.toggle('fixed',!!page().buttons?.some(button=>button.index===index));key.classList.toggle('reserved',index===10||index===14);});$('selected-index').textContent=String(selectedKey+1).padStart(2,'0');select('button-type').value=b?.type??'empty';$('button-details').hidden=!b;$('target-label').hidden=b?.type!=='page';input('button-label').value=b?.label??'';input('button-position').value=String(selectedKey+1);const target=select('button-target');target.replaceChildren(...board.pages.map(p=>option(p.id,p.title)));target.value=b?.type==='page'?b.pageId:board.defaultPage;keys.forEach((key,i)=>{key.classList.toggle('selected',mode==='edit'&&i===selectedKey);key.draggable=mode==='edit'&&!!page().buttons?.some(b=>b.index===i);key.setAttribute('aria-label',`키 ${i+1}${page().buttons?.find(b=>b.index===i)?.label?`: ${page().buttons!.find(b=>b.index===i)!.label}`:''}`);});}
function release(index:number){if(held.delete(index)){send({type:'key',index,edge:'up'});keys[index]?.classList.remove('held');}}
function releaseAll(){for(const index of [...held])release(index);}
function down(index:number){if(mode==='edit'){selectedKey=index;drawKey();return;}if(!runtime.inputEnabled||held.has(index))return;held.add(index);keys[index]!.classList.add('held');send({type:'key',index,edge:'down'});}
function moveButton(from:number,to:number){if(from===to||!Number.isInteger(to)||to<0||to>14)return;const buttons=page().buttons??[],a=buttons.find(b=>b.index===from),b=buttons.find(b=>b.index===to);if(!a)return;a.index=to;if(b)b.index=from;selectedKey=to;drawKey();changed();}
for(let index=0;index<15;index++){const key=document.createElement('button');key.type='button';key.className='key';const canvas=document.createElement('canvas');canvas.width=72;canvas.height=72;const number=document.createElement('span');number.className='key-number';number.textContent=String(index+1).padStart(2,'0');key.append(canvas,number);$('deck').append(key);keys.push(key);canvases.push(canvas);key.onpointerdown=e=>{if(e.button!==0)return;if(mode==='run')key.setPointerCapture(e.pointerId);down(index);};key.onpointerup=()=>release(index);key.onpointercancel=()=>release(index);key.onlostpointercapture=()=>release(index);key.onkeydown=e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();down(index);}};key.onkeyup=e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();release(index);}};key.onblur=()=>release(index);key.ondragstart=e=>{if(mode!=='edit'||!page().buttons?.some(b=>b.index===index)){e.preventDefault();return;}e.dataTransfer!.setData('text/plain',String(index));};key.ondragover=e=>{if(mode==='edit')e.preventDefault();};key.ondrop=e=>{e.preventDefault();if(mode==='edit'){const raw=e.dataTransfer?.getData('text/plain');if(raw&&/^\d+$/.test(raw))moveButton(Number(raw),index);}};}
window.addEventListener('blur',releaseAll);document.addEventListener('visibilitychange',()=>{if(document.hidden)releaseAll();});
function setMode(next:'run'|'edit'){releaseAll();mode=next;$('run-mode').setAttribute('aria-pressed',String(next==='run'));$('edit-mode').setAttribute('aria-pressed',String(next==='edit'));$('deck-help').textContent=next==='edit'?'키를 선택해 구성하세요. 고정 키는 드래그해서 위치를 바꿀 수 있습니다.':'키를 눌러 페이지 이동과 자동 모드 복귀를 확인하세요.';drawKey();}
$('run-mode').onclick=()=>setMode('run');$('edit-mode').onclick=()=>setMode('edit');
input('page-title').oninput=()=>{page().title=input('page-title').value;$('preview-title').textContent=page().title;drawPages();changed();};
input('page-id').onchange=()=>{const old=selected,next=input('page-id').value;if(board.pages.some(p=>p.id===next&&p.id!==old)){fieldErrors.set('page-id','이미 사용 중인 페이지 ID입니다. 다른 ID를 입력하세요.');error(fieldErrors.get('page-id'));return;}fieldErrors.delete('page-id');page().id=next;selected=next;if(board.defaultPage===old)board.defaultPage=next;for(const p of board.pages)for(const b of p.buttons??[])if(b.type==='page'&&b.pageId===old)b.pageId=next;drawPages();drawKey();changed();};
input('default-page').onchange=()=>{if(input('default-page').checked){board.defaultPage=selected;drawPages();changed();}else input('default-page').checked=true;};
$('add-page').onclick=()=>{if(board.pages.length>=32){error('페이지는 최대 32개까지 만들 수 있습니다.');return;}let n=1;while(board.pages.some(p=>p.id===`page-${n}`))n++;selected=`page-${n}`;board.pages.push({id:selected,title:`새 페이지 ${n}`,signals:{}});drawControls();changed();};
$('delete-page').onclick=()=>{if(board.pages.length<=1)return;const removed=selected;board.pages=board.pages.filter(p=>p.id!==removed);selected=board.pages[0]!.id;if(board.defaultPage===removed)board.defaultPage=selected;for(const p of board.pages)p.buttons=p.buttons?.filter(b=>b.type!=='page'||b.pageId!==removed);drawControls();changed();$('notice').textContent='페이지와 해당 페이지로 이동하는 고정 키를 삭제했습니다. 저장 전까지 실제 설정은 유지됩니다.';};
function updateMatch(){const match:NonNullable<PageDefinition['match']>={};if(input('app-bundle').value)match.appBundleId=input('app-bundle').value;if(input('window-value').value)match.windowTitle={mode:select('window-mode').value as 'equals'|'contains',value:input('window-value').value};if(input('display-match').value)match.displayId=input('display-match').value;if(Object.keys(match).length)page().match=match;else delete page().match;page().priority=Number(input('rule-priority').value);drawPages();changed();}
for(const id of ['app-bundle','window-value','display-match','rule-priority'])input(id).oninput=updateMatch;select('window-mode').onchange=updateMatch;
select('signal-source').onchange=()=>{const value=select('signal-source').value;if(value==='__none')delete page().signals;else page().signals=value==='__all'?{}:{source:value};changed();};
select('button-type').onchange=()=>{const type=select('button-type').value;page().buttons=(page().buttons??[]).filter(b=>b.index!==selectedKey);let button:PageButton|undefined;if(type==='text')button={index:selectedKey,type:'text',label:'텍스트'};if(type==='page')button={index:selectedKey,type:'page',pageId:board.pages.find(p=>p.id!==selected)?.id??selected};if(type==='auto')button={index:selectedKey,type:'auto'};if(button)page().buttons!.push(button);drawKey();changed();};
input('button-label').oninput=()=>{const b=page().buttons?.find(b=>b.index===selectedKey);if(b){const label=input('button-label').value;if(b.type==='text'||label)b.label=label;else delete b.label;changed();}};
select('button-target').onchange=()=>{const b=page().buttons?.find(b=>b.index===selectedKey);if(b?.type==='page'){b.pageId=select('button-target').value;changed();}};
input('button-position').onchange=()=>{const to=Number(input('button-position').value)-1;if(!Number.isInteger(to)||to<0||to>14){fieldErrors.set('position','키 위치는 1–15 사이의 정수로 입력하세요.');error(fieldErrors.get('position'));return;}fieldErrors.delete('position');moveButton(selectedKey,to);};
$('remove-button').onclick=()=>{page().buttons=(page().buttons??[]).filter(b=>b.index!==selectedKey);drawKey();changed();};
select('transition').onchange=()=>{board.transition=select('transition').value as 'fade'|'none';input('duration').disabled=board.transition==='none';changed();};input('duration').oninput=()=>{board.durationMs=Number(input('duration').value);changed();};
function context(){send({type:'context',appBundleId:select('active-app').value||null,available:!input('context-unavailable').checked,windowTitle:input('active-title').value||null,displayId:input('active-display').value||null});}
select('active-app').onchange=context;input('active-title').oninput=context;input('active-display').oninput=context;input('context-unavailable').onchange=context;input('locked').onchange=()=>{releaseAll();send({type:'lock',locked:input('locked').checked});};$('auto').onclick=()=>{releaseAll();clearTimeout(timer);if(valid()){send({type:'draft',board,selectedPage:selected});send({type:'auto'});}};input('latency').oninput=()=>{$('latency-value').textContent=`${input('latency').value} ms`;send({type:'latency',ms:Number(input('latency').value)});};input('signals').oninput=()=>{$('signals-value').textContent=`${input('signals').value}개`;send({type:'signals',count:Number(input('signals').value)});};
async function reconnect(){try{const response=await fetch('/api/bootstrap',{cache:'no-store'});if(!response.ok)throw new Error();const data=await response.json();token=data.token;sources=data.sources;connect();}catch{setTimeout(()=>void reconnect(),3000);}}
function connect(){ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/api/simulator`,['streamhub',token]);ws.onopen=()=>{$('connection').classList.add('online');$('connection').lastChild!.textContent=' 연결됨';if(valid())send({type:'draft',board,selectedPage:selected});context();send({type:'latency',ms:Number(input('latency').value)});send({type:'signals',count:Number(input('signals').value)});send({type:'lock',locked:input('locked').checked});};ws.onclose=()=>{releaseAll();runtime.inputEnabled=false;$('connection').classList.remove('online');$('connection').lastChild!.textContent=' 재연결 중';$('runtime-state').textContent='연결 끊김 · 입력 중지';setTimeout(()=>void reconnect(),1500);};ws.onmessage=event=>{try{const message=JSON.parse(event.data);if(message.type==='key'){const canvas=canvases[message.index];if(!canvas||typeof message.rgb!=='string')return;const binary=atob(message.rgb);if(binary.length!==72*72*3)return;const rgba=new Uint8ClampedArray(72*72*4);for(let i=0,j=0;i<binary.length;i+=3,j+=4){rgba[j]=binary.charCodeAt(i);rgba[j+1]=binary.charCodeAt(i+1);rgba[j+2]=binary.charCodeAt(i+2);rgba[j+3]=255;}canvas.getContext('2d')!.putImageData(new ImageData(rgba,72,72),0,0);}else if(message.type==='standby'){for(const canvas of canvases){const ctx=canvas.getContext('2d')!;ctx.fillStyle='#080f19';ctx.fillRect(0,0,72,72);ctx.fillStyle='#667b9e';ctx.font='10px sans-serif';ctx.textAlign='center';ctx.fillText('대기',36,39);}}else if(message.type==='state'){runtime=message;const name=board.pages.find(p=>p.id===message.pageId)?.title??message.pageId;$('runtime-state').textContent=message.locked?'잠김 · 대기화면':`${name} · ${message.manual?'수동 고정':'자동 선택'}${message.inputEnabled?'':' · 전송 중'}${message.manual?'':` · ${message.selectionReason??''}`}`;$('frames').textContent=String(message.frames??0);$('keys-sent').textContent=String(message.keysSent??0);$('frame-ms').textContent=`${Math.round(message.lastFrameMs??0)} ms`;}else if(message.type==='error')error(message.message);}catch{error('시뮬레이터 응답을 읽지 못했습니다. 다시 불러오기를 시도하세요.');}};}
async function load(){try{const response=await fetch('/api/bootstrap',{cache:'no-store'});if(!response.ok)throw new Error('설정을 불러오지 못했습니다.');const data=await response.json();board=validatePageConfig(data.board);sources=data.sources;version=data.version;token=data.token;saved=JSON.stringify(board);history.reset(board);historyStatus();selected=board.defaultPage;ready=true;error();drawControls();if(!ws)connect();else if(ws.readyState===WebSocket.OPEN)send({type:'draft',board,selectedPage:selected});}catch(e){error((e as Error).message);}}
$('reload').onclick=()=>{if(!dirty()||confirm('저장하지 않은 변경을 버리고 저장된 설정을 불러올까요?'))void load();};
$('save').onclick=async()=>{if(!valid()||saving)return;saving=true;status();const submitted=JSON.stringify(board);try{const response=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json','X-Streamhub-Editor':token},body:JSON.stringify({board,version})});const result=await response.json();if(response.status===409)throw new Error('다른 곳에서 설정이 변경되었습니다. 현재 편집 내용은 유지됩니다. JSON으로 내보낸 뒤 다시 불러오기로 최신 설정을 확인하세요.');if(!response.ok)throw new Error(result.error??'설정을 저장하지 못했습니다.');version=result.version;saved=JSON.stringify(validatePageConfig(result.board));if(JSON.stringify(board)===submitted){board=validatePageConfig(result.board);drawControls();}error();$('notice').textContent='설정을 저장했습니다. 실행 중인 Streamhub 호스트를 다시 시작하면 실제 장치에 적용됩니다.';}catch(e){error((e as Error).message);}finally{saving=false;status();}};
$('import').onclick=()=>input('import-file').click();input('import-file').onchange=async()=>{const file=input('import-file').files?.[0];if(!file)return;try{if(file.size>1024*1024)throw new Error('JSON 파일은 1MB 이하로 선택하세요.');const imported=validatePageConfig(JSON.parse(await file.text()));board=imported;selected=board.defaultPage;drawControls();changed();}catch(e){error(`가져오기 실패: ${(e as Error).message}`);}finally{input('import-file').value='';}};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(board,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='streamhub-pages.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.addEventListener('beforeunload',e=>{releaseAll();if(dirty()&&ready){e.preventDefault();e.returnValue='';}});
$('reduced-motion').hidden=!matchMedia('(prefers-reduced-motion: reduce)').matches;
void load();

$('check-draft').onclick=async()=>{if(!valid())return;const button=$<HTMLButtonElement>('check-draft');button.disabled=true;button.textContent='검증 중…';try{const response=await fetch('/api/check',{method:'POST',headers:{'Content-Type':'application/json','X-Streamhub-Editor':token},body:JSON.stringify({board})});const result=await response.json();if(!response.ok)throw new Error(result.error);$('notice').textContent=result.checks.map((check:{name:string;status:string})=>`${check.status.toUpperCase()} ${check.name}`).join(' · ');const link=$<HTMLAnchorElement>('check-report');link.href=result.report;link.hidden=false;}catch(e){error(String(e));}finally{button.disabled=false;button.textContent='초안 검증';}};

function historyStatus(){$<HTMLButtonElement>('undo').disabled=!history.canUndo;$<HTMLButtonElement>('redo').disabled=!history.canRedo;}
function restoreDraft(next:PageConfig){releaseAll();board=next;if(!board.pages.some(p=>p.id===selected))selected=board.defaultPage;drawControls();historyStatus();if(valid())send({type:'draft',board,selectedPage:selected});}
$('undo').onclick=()=>{const next=history.undo();if(next)restoreDraft(next);};$('redo').onclick=()=>{const next=history.redo();if(next)restoreDraft(next);};
$('duplicate-page').onclick=()=>{try{const result=duplicatePage(board,selected);board=result.board;selected=result.selected;drawControls();changed();}catch(e){error(String(e));}};
for(const [id,offset] of [['page-up',-1],['page-down',1]] as const)$(id).onclick=()=>{try{board=movePage(board,selected,offset);drawControls();changed();}catch(e){error(String(e));}};
$('add-template').onclick=()=>{try{const kind=select('template-kind').value as 'all'|'source'|'tools';const result=createTemplate(board,kind,page().signals?.source??sources[0]);board=result.board;selected=result.selected;drawControls();changed();}catch(e){error(String(e));}};
$('copy-key').onclick=()=>{const key=page().buttons?.find(button=>button.index===selectedKey);if(key){copiedKey=structuredClone(key);$('notice').textContent='고정 키를 복사했습니다. 원하는 자리를 선택하고 붙여넣으세요.';}else error('복사할 고정 키를 선택하세요.');};
$('paste-key').onclick=()=>{if(!copiedKey)return;try{const candidate=structuredClone(board),target=candidate.pages.find(p=>p.id===selected)!;target.buttons=[...(target.buttons??[]).filter(button=>button.index!==selectedKey),{...structuredClone(copiedKey),index:selectedKey}];board=validatePageConfig(candidate);drawKey();changed();}catch(e){error(`붙여넣을 수 없습니다: ${String(e)}`);}};
input('button-color').oninput=()=>{const key=page().buttons?.find(button=>button.index===selectedKey);if(key){key.color=input('button-color').value;changed();}};
select('button-icon').onchange=()=>{const key=page().buttons?.find(button=>button.index===selectedKey);if(key){const value=select('button-icon').value;if(value)key.icon=value as NonNullable<PageButton['icon']>;else delete key.icon;changed();}};
historyStatus();
