import {validateStudioDocument,type DynamicRegion,type StudioButton,type StudioDocument,type TransitionSpec} from '../../studio/document';
export class StudioModel{private past:StudioDocument[]=[];private future:StudioDocument[]=[];private applied:string;document:StudioDocument;selectedPageId:string;selectedKey=0;constructor(document:StudioDocument){this.document=validateStudioDocument(document);this.selectedPageId=this.document.defaultPageId;this.applied=JSON.stringify(this.document);}get dirty(){return JSON.stringify(this.document)!==this.applied;}private change(mutator:(draft:StudioDocument)=>void){this.past.push(structuredClone(this.document));if(this.past.length>100)this.past.shift();this.future=[];const draft=structuredClone(this.document);mutator(draft);this.document=validateStudioDocument(draft);}
  selectPage(id:string){if(this.document.pages.some(p=>p.id===id))this.selectedPageId=id;}selectKey(index:number){if(Number.isInteger(index)&&index>=0&&index<15)this.selectedKey=index;}
  addPage(){let n=2;while(this.document.pages.some(p=>p.id===`page-${n}`))n++;const id=`page-${n}`;this.change(d=>d.pages.push({id,title:`페이지 ${n}`}));this.selectedPageId=id;}
  setBackground(target:'page'|'standby',assetId:string,fit:'cover'|'contain'|'stretch'='cover'){this.change(d=>{const appearance=target==='standby'?d.standby:(d.pages.find(p=>p.id===this.selectedPageId)!.appearance??={});appearance.background={assetId,fit};});}
  setButton(button:StudioButton){this.change(d=>{const p=d.pages.find(p=>p.id===this.selectedPageId)!;p.buttons=[...(p.buttons??[]).filter(b=>b.index!==button.index),button];});}
  removeButton(index:number){this.change(d=>{const p=d.pages.find(p=>p.id===this.selectedPageId)!;p.buttons=p.buttons?.filter(b=>b.index!==index);});}
  setDynamicRegion(region:DynamicRegion){this.change(d=>{const p=d.pages.find(p=>p.id===this.selectedPageId)!;p.dynamicRegions=[...(p.dynamicRegions??[]).filter(r=>r.id!==region.id),region];});}
  setMotion(trigger:keyof StudioDocument['motion'],spec:TransitionSpec){this.change(d=>{d.motion[trigger]=spec;});}
  undo(){const previous=this.past.pop();if(previous){this.future.push(structuredClone(this.document));this.document=previous;}}redo(){const next=this.future.pop();if(next){this.past.push(structuredClone(this.document));this.document=next;}}markApplied(){this.applied=JSON.stringify(this.document);}
}
