import {expect,test} from 'bun:test';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {SignalStore} from './store';import {startPresentationService} from './presentation';
test('presentation service publishes, handles lock/unlock and safe key release',async()=>{const dir=mkdtempSync(join(tmpdir(),'streamhub-presentation-')),store=new SignalStore(':memory:'),sent:any[]=[],effects:any[]=[];let service:Awaited<ReturnType<typeof startPresentationService>>|undefined;try{service=await startPresentationService({store,directory:dir,gateway:{publish:m=>sent.push(m),status:()=>({connected:true})},execute:async e=>{effects.push(e)}});expect(sent.at(-1)).toMatchObject({type:'presentation',trigger:'initial'});await service.message({v:1,type:'lock',locked:true});expect(sent.at(-1)).toMatchObject({trigger:'standby'});await service.message({v:1,type:'lock',locked:false});expect(sent.at(-1)).toMatchObject({trigger:'unlock'});const snap=service.snapshot();const doc=structuredClone(snap.document);doc.pages[0].buttons=[{id:'firefox',index:0,action:{type:'open-app',bundleId:'org.mozilla.firefox'},appearance:{contentMode:'hidden'}}];await service.apply(doc,snap.version);const generation=service.status().generation!;await service.message({v:1,type:'key',phase:'down',index:0,generation});await service.message({v:1,type:'key',phase:'up',index:0,generation});expect(effects).toEqual([{type:'app',bundleId:'org.mozilla.firefox'}]);}finally{await service?.stop();store.close();rmSync(dir,{recursive:true,force:true});}});

test('presentation records stable system failures and lock cancels pending execution',async()=>{
  const dir=mkdtempSync(join(tmpdir(),'streamhub-presentation-')),store=new SignalStore(':memory:'),sent:any[]=[];let mode:'fail'|'wait'='fail',received:AbortSignal|undefined,release:()=>void=()=>{};
  const service=await startPresentationService({store,directory:dir,gateway:{publish:message=>sent.push(message),status:()=>({connected:true})},execute:async(_effect,signal)=>{received=signal;if(mode==='fail')throw Object.assign(new Error('permission'),{code:'accessibility-permission-required'});await new Promise<void>(resolve=>{release=resolve;signal?.addEventListener('abort',()=>resolve(),{once:true});});}});
  try{
    const snapshot=service.snapshot(),document=structuredClone(snapshot.document);document.pages[0].buttons=[{id:'hotkey',index:0,action:{type:'hotkey',keys:['command','k']},appearance:{contentMode:'hidden'}}];await service.apply(document,snapshot.version);
    let generation=service.status().generation!;await service.message({v:1,type:'key',phase:'down',index:0,generation});await expect(service.message({v:1,type:'key',phase:'up',index:0,generation})).resolves.toBeUndefined();expect(sent.at(-1)).toMatchObject({trigger:'refresh'});
    mode='wait';const next=service.snapshot(),changed=structuredClone(next.document);changed.pages[0].buttons![0].id='hotkey-2';await service.apply(changed,next.version);generation=service.status().generation!;await service.message({v:1,type:'key',phase:'down',index:0,generation});const pending=service.message({v:1,type:'key',phase:'up',index:0,generation});await Bun.sleep(0);await service.message({v:1,type:'lock',locked:true});expect(received?.aborted).toBe(true);release();await expect(pending).resolves.toBeUndefined();
  }finally{await service.stop();store.close();rmSync(dir,{recursive:true,force:true});}
});
