import {expect,test} from 'bun:test';
import {mkdtempSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import type {DeckBackend,DeckBackendKind} from '../../presentation/backend';
import {startHost,type HostDependencies} from './runtime';
import {SignalStore} from './store';
import type {Config} from './config';

const config:Config={port:31415,adminToken:'a'.repeat(32),sources:{demo:{token:'b'.repeat(32)}},display:{mode:'off'}};
const fakeBackend=(mode:DeckBackendKind,state:'ready'|'unavailable'='ready',stop:()=>Promise<void>=async()=>{}):DeckBackend=>({async prepare(request){return{backend:mode,generation:request.generation,token:request.generation};},async present(){},status:()=>({mode,state,connected:state==='ready'}),stop});
const deferred=<T>()=>{let resolve!:(value:T)=>void;let reject!:(error:unknown)=>void;const promise=new Promise<T>((done,fail)=>{resolve=done;reject=fail;});return{promise,resolve,reject};};
function resources(){const calls:string[]=[];let store!:SignalStore;const dependencies:Partial<HostDependencies>={openStore:()=>{calls.push('store-open');store=new SignalStore(':memory:');const close=store.close.bind(store);store.close=()=>{calls.push('store-close');close();};return store;},serve:()=>{calls.push('server-open');return{url:new URL('http://127.0.0.1:31415'),stop:async()=>{calls.push('server-stop');}};}};return{calls,dependencies,get store(){return store;}};}
const monitors=(dependencies:Partial<HostDependencies>)=>Object.assign(dependencies,{sessionMonitor:async()=>({stop:async()=>{}}),contextMonitor:async()=>({stop:async()=>{}})});

test('runtime validates supplied configuration before acquiring any resources',async()=>{const r=resources();await expect(startHost({...config,adminToken:'short'},'/unused',{dependencies:r.dependencies})).rejects.toThrow();expect(r.calls).toEqual([]);});
test('runtime rollback closes store when server startup fails',async()=>{const r=resources();r.dependencies.serve=()=>{throw new Error('bind failed');};await expect(startHost(config,'/unused',{dependencies:r.dependencies})).rejects.toThrow('bind failed');expect(r.calls).toEqual(['store-open','store-close']);});
test('shutdown drains an in-flight collector before closing its store',async()=>{const r=resources(),started=deferred<void>(),gate=deferred<{ids:string[];discoveries:[]}>();r.dependencies.collect=async()=>{started.resolve();return gate.promise;};const host=await startHost({...config,collectors:[{source:'demo',exec:['/usr/bin/true'],intervalMs:1000}]},'/unused',{dependencies:r.dependencies});await started.promise;const stopping=host.stop();await Bun.sleep(0);expect(r.calls).not.toContain('store-close');gate.resolve({ids:[],discoveries:[]});await stopping;expect(r.calls.at(-1)).toBe('store-close');});
test('abort during selected backend startup cleans up the late backend',async()=>{const directory=mkdtempSync(join(tmpdir(),'streamhub-runtime-abort-')),r=resources(),controller=new AbortController(),started=deferred<void>(),gate=deferred<DeckBackend>();try{monitors(r.dependencies);r.dependencies.hidBackend=async()=>{started.resolve();return gate.promise;};const starting=startHost({...config,display:{mode:'hid'}},directory,{dependencies:r.dependencies,signal:controller.signal});await started.promise;controller.abort();await Bun.sleep(0);expect(r.calls).not.toContain('store-close');gate.resolve(fakeBackend('hid','ready',async()=>{r.calls.push('late-backend-stop');}));await expect(starting).rejects.toMatchObject({name:'AbortError'});expect(r.calls).toContain('late-backend-stop');expect(r.calls.at(-1)).toBe('store-close');}finally{rmSync(directory,{recursive:true,force:true});}});
test('runtime constructs only the selected canonical backend',async()=>{const directory=mkdtempSync(join(tmpdir(),'streamhub-runtime-mode-')),tokenFile=join(directory,'plugin-token');writeFileSync(tokenFile,'x'.repeat(64),{mode:0o600});try{for(const mode of ['hid','plugin','off'] as const){const r=resources(),calls={hid:0,plugin:0};monitors(r.dependencies);Object.assign(r.dependencies,{hidBackend:async()=>{calls.hid++;return fakeBackend('hid');},pluginBackend:async()=>{calls.plugin++;return fakeBackend('plugin');}});const display=mode==='plugin'?{mode,plugin:{port:31417,tokenFile}}:{mode};const host=await startHost({...config,display},directory,{dependencies:r.dependencies});expect(calls).toEqual(mode==='hid'?{hid:1,plugin:0}:mode==='plugin'?{hid:0,plugin:1}:{hid:0,plugin:0});await host.stop();}}finally{rmSync(directory,{recursive:true,force:true});}});
test('an unavailable selected backend never constructs the other owner',async()=>{const directory=mkdtempSync(join(tmpdir(),'streamhub-runtime-unavailable-'));try{const r=resources(),calls={hid:0,plugin:0};monitors(r.dependencies);Object.assign(r.dependencies,{hidBackend:async()=>{calls.hid++;return fakeBackend('hid','unavailable');},pluginBackend:async()=>{calls.plugin++;return fakeBackend('plugin');}});const host=await startHost({...config,display:{mode:'hid'}},directory,{dependencies:r.dependencies});expect(calls).toEqual({hid:1,plugin:0});await host.stop();}finally{rmSync(directory,{recursive:true,force:true});}});
test('stop is shared and attempts selected backend, server, and store cleanup once',async()=>{const directory=mkdtempSync(join(tmpdir(),'streamhub-runtime-stop-'));try{const r=resources();monitors(r.dependencies);r.dependencies.hidBackend=async()=>fakeBackend('hid','ready',async()=>{r.calls.push('backend-stop');throw new Error('backend close failed');});r.dependencies.serve=()=>({url:new URL('http://127.0.0.1:31415'),stop:async()=>{r.calls.push('server-stop');throw new Error('server close failed');}});const host=await startHost({...config,display:{mode:'hid'}},directory,{dependencies:r.dependencies});const first=host.stop(),second=host.stop();expect(second).toBe(first);await expect(first).rejects.toBeInstanceOf(AggregateError);expect(r.calls.filter(call=>call==='backend-stop')).toHaveLength(1);expect(r.calls.filter(call=>call==='server-stop')).toHaveLength(1);expect(r.calls.at(-1)).toBe('store-close');}finally{rmSync(directory,{recursive:true,force:true});}});
