import {playFramePlan} from '../../presentation/playback';import {parseRuntimeMessage,type PluginToRuntimeMessage,type RuntimeToPluginMessage} from '../../presentation/protocol';import type {PresentationMessage} from './cache';
type Cell={setImage(image:string):Promise<unknown>};type Cache={save(message:PresentationMessage):void;load():PresentationMessage|undefined};
export class CanvasController{private cells=new Map<number,Cell>();private generation='offline';private input=false;private online=false;private announced=false;private playback?:AbortController;constructor(private options:{send(message:PluginToRuntimeMessage):void;cache:Cache;deviceId?:string}){}
  private ready(){if(!this.online||this.announced||this.cells.size<15)return;this.announced=true;this.options.send({v:1,type:'cells-ready',deviceId:this.options.deviceId??'streamdeck-classic'});}
  connection(connected:boolean){if(this.online===connected)return;this.online=connected;if(!connected){this.announced=false;this.input=false;this.playback?.abort();return;}this.ready();}
  async appear(index:number,cell:Cell){if(!Number.isInteger(index)||index<0||index>14)return;this.cells.set(index,cell);const cached=this.options.cache.load();if(cached)await cell.setImage(cached.plan.frames.at(-1)!.keys[index]!);this.ready();}
  disappear(index:number,cell:unknown){if(this.cells.get(index)!==cell)return;this.cells.delete(index);if(this.cells.size===0){this.announced=false;this.input=false;this.playback?.abort();}}
  async receive(raw:unknown){const message=parseRuntimeMessage(raw);if(message.type==='ping'){this.options.send({v:1,type:'pong'});return;}if(message.type==='input'){this.input=message.enabled;return;}this.options.cache.save(message);this.playback?.abort();const controller=this.playback=new AbortController();this.generation=message.plan.generation;this.input=false;if(this.cells.size<15)return;await playFramePlan(message.plan,async frame=>{await Promise.all(Array.from({length:15},(_,index)=>this.cells.get(index)!.setImage(frame.keys[index]!)));this.options.send({v:1,type:'frame-sent',generation:message.plan.generation,frame:frame.index});},{signal:controller.signal});if(!controller.signal.aborted)this.input=message.inputEnabled;}
  key(index:number,phase:'down'|'up'){if(this.input&&this.cells.has(index))this.options.send({v:1,type:'key',phase,index,generation:this.generation});}
}
