import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {createInterface} from 'node:readline/promises';
import {readConfig,type DisplayMode} from '../packages/host/src/config';
import type {StudioDisplayStatus} from '../packages/host/src/runtime';

type CheckedMode=Exclude<DisplayMode,'off'>;
type Observation={checkedAt:string;mode:CheckedMode;observationStartedAt:string;recoveringAt:string;readyAt:string;elapsedMs:number;passed:boolean};
export function parseDisplayModeArgs(args:readonly string[]):CheckedMode{if(args.length!==2||args[0]!=='--mode'||(args[1]!=='hid'&&args[1]!=='plugin'))throw new Error('Usage: bun run display:check --mode hid|plugin');return args[1];}
export const recoveryBound=(mode:CheckedMode)=>mode==='hid'?1000:3000;
export function publicStatus(value:unknown):StudioDisplayStatus{if(!value||typeof value!=='object')throw new Error('Runtime display status is unavailable');const status=value as Partial<StudioDisplayStatus>;if(!['off','hid','plugin'].includes(status.configuredMode as string)||!['off','hid','plugin'].includes(status.activeMode as string)||!['off','connecting','ready','recovering','unavailable'].includes(status.state as string)||typeof status.restartRequired!=='boolean')throw new Error('Runtime returned an invalid display status');return{configuredMode:status.configuredMode!,activeMode:status.activeMode!,state:status.state!,restartRequired:status.restartRequired,...(typeof status.message==='string'?{message:status.message}:{})};}

async function run(){const mode=parseDisplayModeArgs(process.argv.slice(2)),config=readConfig();if(config.display.mode!==mode)throw new Error(`설정된 모드는 ${config.display.mode}입니다. Studio에서 ${mode} 모드를 저장한 뒤 Runtime을 다시 시작하세요.`);const status=async()=>{const response=await fetch(`http://127.0.0.1:${config.port}/v1/state`,{headers:{authorization:`Bearer ${config.adminToken}`},signal:AbortSignal.timeout(1000)});if(!response.ok)throw new Error(`Runtime status failed: ${response.status}`);return publicStatus((await response.json() as {display?:unknown}).display);};const initial=await status();console.log(JSON.stringify(initial,null,2));if(initial.configuredMode!==mode||initial.activeMode!==mode)throw new Error('현재 Runtime이 요청한 모드의 장치를 소유하지 않습니다. Runtime을 다시 시작하세요.');if(initial.state==='unavailable')throw new Error(initial.message??'선택한 디스플레이를 사용할 수 없습니다.');console.log(mode==='hid'?'Stream Deck 앱을 완전히 종료한 상태를 유지하세요.':'Stream Deck 앱과 Streamhub 프로필을 실행한 상태를 유지하세요.');const input=createInterface({input:process.stdin,output:process.stdout});try{await input.question('Enter를 누른 뒤 Mac을 잠갔다가 바로 잠금 해제하세요. ');}finally{input.close();}const waitUntil=performance.now()+60_000;let observationStarted:number|undefined,recovering:number|undefined,ready:number|undefined;while(performance.now()<waitUntil){const current=await status(),now=performance.now();if(current.state==='recovering'&&recovering===undefined){recovering=now;observationStarted=now;}if(recovering!==undefined&&current.state==='ready'){ready=now;break;}if(observationStarted!==undefined&&now-observationStarted>recoveryBound(mode)+250)break;await Bun.sleep(25);}if(observationStarted===undefined||recovering===undefined||ready===undefined)throw new Error('recovering → ready 잠금 복구를 제한 시간 안에 관찰하지 못했습니다.');const elapsedMs=ready-observationStarted,bound=recoveryBound(mode),now=new Date(),observation:Observation={checkedAt:now.toISOString(),mode,observationStartedAt:new Date(now.getTime()-(ready-observationStarted)).toISOString(),recoveringAt:new Date(now.getTime()-(ready-recovering)).toISOString(),readyAt:now.toISOString(),elapsedMs,passed:elapsedMs<=bound};mkdirSync('.streamhub',{recursive:true,mode:0o700});const path='.streamhub/display-mode-check.json';let history:Observation[]=[];try{const parsed=JSON.parse(readFileSync(path,'utf8'));if(Array.isArray(parsed))history=parsed.filter(item=>item&&typeof item==='object').slice(-99);}catch{}history.push(observation);writeFileSync(path,JSON.stringify(history,null,2)+'\n',{mode:0o600});console.log(`${mode.toUpperCase()} recovery: ${elapsedMs.toFixed(1)} ms / ${bound} ms`);if(!observation.passed)throw new Error(`${mode} recovery exceeded ${bound} ms`);console.log(`PASS: 결과를 ${path}에 저장했습니다.`);}

if(import.meta.main)await run();
